apiVersion: v1
kind: Namespace
metadata:
  name: nextjs-template
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nextjs-template
  namespace: nextjs-template
data:
  NODE_ENV: "production"
  PORT: "3000"
  npm_package_version: "0.1.0"
---
apiVersion: v1
kind: Secret
metadata:
  name: nextjs-template
  namespace: nextjs-template
type: Opaque
stringData:
  DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/nextjs?schema=public"
